##
# Set of re-usable rules for decidim module development. 
# You are required to set the following CI/CD variables: 
# 
# - CROWDIN_PERSONAL_TOKEN: protected & masked. // API Token from crowdin
# - CROWDIN_PROJECT_ID: masked. // Project ID from crowdin
# - TRANSLATIONBOT_ID: masked. // Project Bot `mr-translation` user id (see in repo>members tab)
# - TRANSLATIONBOT_ACCESS_TOKEN: masked. // Project Token with name `mr-translations`
# - GEM_HOST_API_KEY: protected & masked. // 
stages:
  - lint
  - translate
  - publish

.development_rules:  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
.publication_rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
##
# Lint ruby code
ruby::rubocop:  
  extends: .development_rules
  image: ruby:3.2.7
  stage: lint
  script:
    - bundle
    - bundle exec rubocop .
##
# Publish the gem un ruby gem.
ruby::rubygem:
  image: ruby
  stage: publish
  script:
    - echo "---" > .credentials
    - |
      echo ":ci_rubygems_api_key: $GEM_HOST_API_KEY" >> .credentials
    - chmod 0600 .credentials
    - gem build decidim-decidim_better_accountability.gemspec
    - gem push decidim-decidim_better_accountability-*.gem -k ci_rubygems_api_key --config-file .credentials
  only:
    - tags

crowdin::upload:
  stage: translations
  image: node:20
  when: manual
  script:
    - npm install -g @crowdin/cli
    - crowdin upload -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress || exit 1
    - crowdin status -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress || exit 1

# Create a MR with the new translation
crowdin::merge_request:
  stage: translations
  image: node:20
  when: manual
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - git config --global user.email "mr-translations"
    - git config --global user.name "$GIT_USERNAME"
    - npm install -g @crowdin/cli
    - crowdin download  -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress
    - crowdin status -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress || exit 1
    - export BRANCH_NAME="i18n/$(date +%Y%m%d%H%M%S)"
    - export ORIGIN="crowndin_$(date +%Y%m%d%H%M%S)"
    - echo "add $ORIGIN=https://$GIT_USERNAME:$ACCESS_TOKEN@git.octree.ch/$CI_PROJECT_PATH.git"
    - git remote add $ORIGIN https://$GIT_USERNAME:$ACCESS_TOKEN@git.octree.ch/$CI_PROJECT_PATH.git
    - git checkout -b $BRANCH_NAME
    - git add config/locales
    - git commit -m "Update translations"
    - git push $ORIGIN HEAD:$BRANCH_NAME -o merge_request.create -o merge_request.target=main
