#
# Your Crowdin credentials
#
base_path: .
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_url: https://api.crowdin.com
project_id: "717881"

#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files: [
  {
    "source": "/config/locales/decidim-better-accountability.en.yml",
    "translation": "/config/locales/decidim-better-accountability.%two_letters_code%.yml",
  }
]