services:
  decidim-better-acccountability:
    container_name: decidim-better-acccountability
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/decidim/module
      - bundle:/home/decidim/app/vendor
      - node_modules:/home/decidim/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@better-accountability-pg:5432/decidim
      - DEV_MODULE=decidim-decidim_better_accountability
      - RAILS_ENV=development
    ports:
      - 3000:3000
    links:
      - better-accountability-pg
    depends_on:
      - better-accountability-pg

  better-accountability-pg:
    container_name: better-accountability-pg
    image: postgres:16
    volumes:
      - better-acccountability-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe

volumes:
  node_modules: {}
  bundle: {}
  better-acccountability-pg-data: {}
